### ISSUE TITLE
anchor/link tag feature? 

### ISSUE THREAD

**Issue by nachonathan** [jediwade/brackets-htmlformat#2]
Would it be possible to add an anchor/link tag feature?

**Comment by jediwade** [comment]
Could you elaborate more on what you had in mind? Were you wanting a keyboard shortcut feature to add an anchor tag around highlighted copy, anchor tag added to the HTML Format drop down menu with the other tags, a right-click feature, etc?

**Comment by nachonathan** [comment]
I think a keyboard shortcut feature to add an anchor tag around highlighted copy and the anchor tag added to the HTML Format drop down menu with the other tags would be perfect. I do a lot of emails, and the legal copy always features a ton of links, so being able highlight words and add a link would be awesome.

**Comment by jediwade** [comment]
I can do that. Email development is actually my primary job and is the very reason this extension was built. I just couldn't fathom, for example, Brackets not having the ability to bold text with a CMD+B. So this extension was spawned from me wanting to switch from Dreamweaver to Brackets, but not without the hotkeys I love so much.

**Comment by jediwade** [comment]
New version uploaded with requested feature.
