### ISSUE TITLE
Extension doesn't get charged

### ISSUE THREAD

**Issue by ktex** [jediwade/brackets-htmlformat#7]
Hi, 

I'm trying to use this usefull extension on Bracket, but it doesn't get charged into Bracket.
Even when I desactivate all my other extension, this one doesn't work.

How can I solve it ?

**Comment by jediwade** [comment]
You need to provide more details for me to try and help. 

What OS are you using and what version is it?
What Brackets version are you using?
What version of this extension are you using?
Did you install this extension through Brackets or did you download and manually install it?
What do you mean by "...it doesn't get **charged** into Bracket"?
By your comment of "this one doesn't work", do you mean that you are not seeing the "HTML Format" menu in the menu bar (located between "Edit" and "Find") or are the keyboard shortcuts not working?

**Comment by ktex** [comment]
hi,
Yes sorry,

So I'm on Windows 10 64x home edition, french language.
Brackets is : Version 1.14 édition 1.14.0-17740 (release 329d08ffc)
I'm trying to use the extension on the brackets repo, so it's : the version 1.0.1 - 20/11/2017

I mean it doesn't get loaded in Brackets toolbar (betweend Edit and Find) and the shortcut doesn't work either (CTRL+B for example, and it's not used in other extension) but in my extensions manager it's already activated.
I desactivated all my other extension, but the problem it's the same, this extension doesn't work.

Sometime my Bracket App get frozen when I launch it, and it doesn't do that when I delete HTMLformat extension (or significantly less often).

I don't know if it's because of your extension, because I got the same problem with the extension "Multi-Line Middle Click", of Momma ReGen, V0.1.2-19/08/2019. But all my others extensions did work properly.


Thanks for fast consideration.

best regards

________________________________
De : Wade <notifications@github.com>
Envoyé : dimanche 10 novembre 2019 14:35
À : jediwade/brackets-htmlformat <brackets-htmlformat@noreply.github.com>
Cc : ktex <ktex@outlook.com>; Author <author@noreply.github.com>
Objet : Re: [jediwade/brackets-htmlformat] Extension doesn't get charged (#7)


You need to provide more details for me to try and help.

What OS are you using and what version is it?
What Brackets version are you using?
What version of this extension are you using?
Did you install this extension through Brackets or did you download and manually install it?
What do you mean by "...it doesn't get charged into Bracket"?
By your comment of "this one doesn't work", do you mean that you are not seeing the "HTML Format" menu in the menu bar (located between "Edit" and "Find") or are the keyboard shortcuts not working?

**Comment by jediwade** [comment]
First, disable all other extensions like you were doing before. Under the "Debug" menu, click "Show Developer Tools" and then click the "Console" tab at the top of the window that just opened. Click anywhere in the Brackets app to give it focus. Click "Reload with Extensions" under the "Debug" menu and tell me what appears in the Console window of the developer tools. There will hopefully be an error message of some sort that can be debug.

**Comment by ktex** [comment]
Nothing change in the console.
All my extension are disabled but when I click on "Reload with extension" or "without Extension" it's seem it does nothing.

I reactivate the Twig extension (to color twig synthax) to see if this function work  when I click on "reload without extension", but it's not working, the twig color extensions is still active. And when I click on that button and reboot Bracket, the Twig extension is still activate
Nothing appear in the console when I click on "Reload W/O extension". But I got this error message when I start Brackets, maybe it could be helpful :

>  /command/Menus.js:991 Error setting menu item shortcut: 1(anonymous function) @ /command/Menus.js:991
> /language/LanguageManager.js:663 Cannot register file extension "twig" for Twig, it already belongs to HTML
> main.js:30 INITIALIZING HTML FORMAT EXTENSION
> /command/KeyBindingManager.js:578 Failed to normalize Cmd-Shift-]
> /command/KeyBindingManager.js:578 Failed to normalize Cmd-Shift-[
> /LiveDevelopment/MultiBrowserImpl/transports/NodeSocketTransport.js:84 NodeSocketTransport - start
> main.js:289 Php tooling: Starting the service
> main.js:309 AutoUpdate : updateHelper.json cannot be parsed, does not exist
> /languageTools/ClientLoader.js:69 C:/Program Files (x86)/Brackets/www/extensions/default/PhpTooling/client.js domain successfully created
> /filesystem/FileSystem.js:1028 File watchers went offline!
> /utils/NodeConnection.js:84 WebSocket connection to 'ws://localhost:54554/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
> main.js:291 Php tooling: Something went wrong. Restarting the service
> /languageTools/ClientLoader.js:69 C:/Program Files (x86)/Brackets/www/extensions/default/PhpTooling/client.js domain successfully created
> 2/utils/NodeConnection.js:84 WebSocket connection to 'ws://localhost:54554/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
> /filesystem/FileSystem.js:1036 Watching disabled for E:/pierr/Téléchargements/Chrome/programmation/Sites/FYD/

**Comment by jediwade** [comment]
When you click "Reload With Extensions" or "Reload Without Extensions", you should see the entire Brackets app window flash white like a website reload. Try clicking into a file you have open, then doing the Reload.

The Console log you gave me didn;t provide much helpful information sadly. I see the "main.js:30 INITIALIZING HTML FORMAT EXTENSION" which means the extension was loaded. I should add a "done initializing" comment at some point so we can know that it finished.

There are some errors related to other built-in features of Brackets, but I don't know if they could cause the problem you are having or not. If there were any errors in the coding of my extension, you would see them there too (I just broke my instance in a few ways to verify errors would appear in the Console).

I have the same "Failed to normalize Ctrl-Shift-]", "Failed to normalize Ctrl-Shift-[", and "main.js:309 AutoUpdate : updateHelper.json cannot be parsed, does not exist" on my Brackets instance.

I'm sorry, but the only advice I can give to you right now is to do a fresh Brackets install.

**Comment by ktex** [comment]
Hi, 
I make a new install of Brackets, with the last version.
I delete all my extension, and install only yours.
HTML Format still not load in Bracket.
Now when I'm clicking on Reload with/without extension, the app flash as you say and reload properly.
In the console, nothing change about this extension, still the : "INITIALIZING HTML FORMAT EXTENSION" with nothing more.

My config is actually only your extension on a complete new installation of Brackets.

**Comment by jediwade** [comment]
Possibly stupid question. Have you opened a ".html", ".htm", ".php", or ".asp" file since installing the extension? My extension only works for those file types.

**Comment by ktex** [comment]
That was that.
I'm working with .html.twig files, but on .html and normal file it's working well.
Because the menu appear in the topbar I've seen that we can add other extension (html.twig in my case) and so I got it on all my files.
You maybe should say on the documentation that we can add other extension by first opening .html file.

Thanks a lot and thanks for you work !
